### ISSUE TITLE
How do you specify which region to create ECR? 

### ISSUE THREAD

**Issue by mhobotpplnet** [seek-oss/create-ecr-buildkite-plugin#7]
I have not tried the plugin yet, but have also not seen where you specify which region should the ECR repo get created in ?

**Comment by 72636c** [comment]
This plugin is uses the AWS CLI, so take a look at the [AWS_DEFAULT_REGION](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) environment variable.

It would be super easy to add an explicit `region` property to the plugin, but setting the environment variable might be the better recommendation especially if you're using AWS tooling in other steps of your pipeline. Thoughts?

**Comment by 72636c** [comment]
Closing for now. Feel free to reopen if you still need this.
